# BÀI 1: LÀM QUEN VỚI PYTORCH

### Bài 1. Tạo Tensor cơ bản

In [20]:
import torch
a = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6]],
    dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


## Giải thích

- **Kích thước:** `torch.Size([2, 3])`, tensor có 2 hàng và 3 cột.
- **Số chiều:** `2`, vì tensor có 2 chiều.
- **Kiểu dữ liệu:** `torch.int32`, các phần tử là số nguyên 32-bit.

### Bài 2. Tạo các Tensor thường dùng

In [21]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

print(a)
print(b)
print(c)
print(d)
print(e)


tensor([[0.3700, 0.5162, 0.1232, 0.2761],
        [0.3862, 0.0122, 0.1158, 0.2686],
        [0.5263, 0.5219, 0.1229, 0.0020]])
tensor([[-1.1577,  0.6439,  0.9350, -2.4415],
        [-1.7912, -0.2692,  0.9010, -0.5377],
        [ 0.9912,  1.4245,  1.6278, -0.5666]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


## Giải thích

- `torch.rand()` tạo tensor có các giá trị ngẫu nhiên theo phân phối đều trong khoảng `[0, 1)`.
- `torch.randn()` tạo tensor có các giá trị ngẫu nhiên theo phân phối chuẩn, với trung bình gần `0` và độ lệch chuẩn gần `1`.
- Tensor `f` có kích thước `5 × 5` và tất cả phần tử đều bằng `10`, được tạo bằng `torch.full((5, 5), 10)`.

### Bài 3. Kiểm tra thông tin Tensor

In [3]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


## Giải thích

`torch.Size([2, 3, 4])` cho biết tensor `a` có **3 chiều**:

- `2`: có 2 khối dữ liệu.
- `3`: mỗi khối có 3 hàng.
- `4`: mỗi hàng có 4 phần tử.

Vì vậy, tensor có dạng `2 × 3 × 4` và chứa tổng cộng `24` phần tử.

### Bài 4. Slicing và Indexing

In [7]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 4.6381e-01,  3.6478e-01,  1.1030e+00, -1.8132e+00, -5.2413e-01],
         [ 5.7984e-01, -7.8293e-01,  1.6475e+00,  1.1144e+00,  1.0470e-01],
         [ 1.5140e-01,  5.2975e-01,  3.1865e-01,  1.0219e+00, -6.6764e-01],
         [ 2.1647e-01,  6.4354e-01,  5.9118e-01, -6.7532e-02,  5.2134e-01]],

        [[-7.9609e-01,  1.1391e+00,  2.3178e-04,  1.2916e+00,  2.7588e-01],
         [-7.0796e-01, -6.4960e-01,  1.7917e+00,  6.3049e-01, -1.6568e+00],
         [-1.0475e+00,  4.3469e-01, -2.2134e+00,  4.9656e-01, -3.4436e-01],
         [ 6.4118e-01,  4.3478e-01, -3.3015e-01,  1.2606e+00,  3.6011e-01]],

        [[ 1.0790e+00, -6.8491e-01,  1.0709e+00, -9.7419e-01,  1.0630e+00],
         [-1.3008e-01, -1.2308e-01, -1.6120e+00,  3.9108e-02, -3.8629e-02],
         [ 1.5010e+00, -3.9777e-01, -3.7807e-01,  4.6581e-01, -1.1626e+00],
         [-8.4151e-01, -9.3829e-03,  1.3434e+00, -4.8195e-01, -7.2489e-02]]])

Tensor a[1]:
tensor([[-7.9609e-01,  1.1391e+00,  2.3178e-04,  1.

## Giải thích

- `a[1]` lấy phần tử tại vị trí `1` trên chiều đầu tiên, nên có shape `torch.Size([4, 5])`.
- `a[1:, 2:4]` lấy từ khối thứ hai trở đi, lấy hàng ở vị trí `2` và `3`, đồng thời giữ toàn bộ chiều cuối; shape là `torch.Size([2, 2, 5])`.
- Để lấy hai phần tử cuối trên chiều thứ ba, dùng `a[:, :, -2:]`.

### Bài 5. Reshape và Flatten

In [8]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.7073,  0.7406,  0.2293,  0.0263],
        [-0.4120,  0.1173, -0.0951,  0.4065],
        [-0.3023, -1.5778, -0.9278, -0.8205]])

Flatten:
tensor([-0.7073,  0.7406,  0.2293,  0.0263, -0.4120,  0.1173, -0.0951,  0.4065,
        -0.3023, -1.5778, -0.9278, -0.8205])

Reshape to 3 x 2 x 2:
tensor([[[-0.7073,  0.7406],
         [ 0.2293,  0.0263]],

        [[-0.4120,  0.1173],
         [-0.0951,  0.4065]],

        [[-0.3023, -1.5778],
         [-0.9278, -0.8205]]])


## Giải thích

- Tensor ban đầu có `3 × 4 = 12` phần tử.
- `a.ravel()` làm phẳng tensor thành một chiều nhưng vẫn giữ nguyên `12` phần tử.
- `a.reshape(3, 2, 2)` đổi hình dạng thành `3 × 2 × 2`, vẫn có `12` phần tử.

### Bài 6. Phép toán và nhân ma trận

In [9]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 0.5601, -0.3763, -2.3025],
        [ 0.7357,  0.2177, -0.1755]])
b:
tensor([[-0.8671, -0.7396, -0.4263],
        [ 1.3380, -1.5360, -1.4273]])

a + b:
tensor([[-0.3070, -1.1159, -2.7287],
        [ 2.0736, -1.3183, -1.6028]])

a / b:
tensor([[-0.6460,  0.5089,  5.4016],
        [ 0.5498, -0.1417,  0.1230]])

a^2:
tensor([[0.3138, 0.1416, 5.3015],
        [0.5412, 0.0474, 0.0308]])

Matrix multiplication:
tensor([[ 0.7741,  4.6139],
        [-0.7241,  0.9004]])


## Giải thích

- `a * b` là phép nhân từng phần tử tương ứng; nếu thực hiện thì kết quả có shape `torch.Size([2, 3])`.
- `a @ b.T` là phép nhân ma trận: `a` có shape `(2, 3)`, `b.T` có shape `(3, 2)`, nên kết quả có shape `torch.Size([2, 2])`.
- Hai phép toán này khác nhau về cách kết hợp các phần tử: một phép nhân từng vị trí, một phép nhân theo hàng và cột.

### Bài 7. Các hàm thống kê trên Tensor

In [10]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 1.0973, -0.2995, -1.6792,  0.3122],
        [-0.2934,  0.2869, -0.0228,  1.7087],
        [ 0.3657,  0.4697,  0.3929,  0.5857]])

Mean:
tensor([ 0.3899,  0.1523, -0.4364,  0.8689])

Standard deviation:
tensor([0.6957, 0.4019, 1.0962, 0.7401])

Cumulative sum:
tensor([[ 1.0973, -0.2995, -1.6792,  0.3122],
        [ 0.8039, -0.0126, -1.7021,  2.0210],
        [ 1.1696,  0.4570, -1.3092,  2.6067]])


## Giải thích

- Với `dim=0`, phép tính được thực hiện theo chiều đầu tiên, nên tensor `(3, 4)` cho kết quả có shape `(4,)`, tương ứng với từng cột.
- `torch.mean` tính giá trị trung bình, `torch.std` tính độ lệch chuẩn, còn `torch.cumsum` tính tổng tích lũy theo chiều được chọn.
- Nếu thay `dim=0` bằng `dim=1`, các phép tính sẽ thực hiện theo từng hàng và kết quả có shape `(3,)`.

### Bài 8. Autograd cơ bản

In [22]:
import torch
x = torch.tensor(
    3.6,
    requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


## Giải thích

- Code đặt `x = 3.6` với `requires_grad=True`, nên PyTorch theo dõi phép tính để tính đạo hàm.
- Với `y = x²`, đạo hàm là `dy/dx = 2x`. Tại `x = 3.6`, giá trị thủ công là `7.2`, khớp với `x.grad`.
- `y.backward()` thực hiện lan truyền ngược để tính gradient.

### Bài 9. Gradient Descent tìm hệ số đa thức

In [23]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.0593],
        [ 1.0635],
        [-1.5551]], requires_grad=True)
Learned coefficients:
tensor([[1.0176],
        [2.0986],
        [1.4533]], requires_grad=True)


## Giải thích

- Ba hệ số trong `w` lần lượt là hệ số của `x²`, `x` và hằng số, nên được so sánh với `[1, 2, 3]`.
- `optimizer.zero_grad()` xóa gradient của vòng lặp trước.
- `mse.backward()` tính gradient của hàm mất mát `mse` theo `w`.
- `optimizer.step()` cập nhật các hệ số `w` để giảm sai số.

### Bài 10. Giải hệ phương trình bằng Autograd

In [19]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
optimizer.zero_grad()
sqerr.backward()
optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = 4.429948806762695
B = 4.5699992179870605
C = 3.570021629333496
D = 2.57000732421875
Residuals:
A + B - 9 = -5.14984130859375e-05
C - D - 1 = 1.430511474609375e-05
A + C - 8 = -2.956390380859375e-05
B - D - 2 = -8.106231689453125e-06


## Giải thích

- `y1`, `y2`, `y3` và `y4` là độ lệch của bốn phương trình so với vế phải tương ứng.
- Khi các residual gần `0`, các giá trị `A`, `B`, `C`, `D` gần thỏa mãn: `A + B = 9`, `C - D = 1`, `A + C = 8` và `B - D = 2`.
- Bốn phương trình không độc lập hoàn toàn nên hệ có thể có nhiều nghiệm. Đặt `A = t` thì một họ nghiệm là `B = 9 - t`, `C = 8 - t`, `D = 7 - t`.

### Bài 11. Tổng hợp các thao tác với Tensor

In [25]:
import numpy as np
import torch

# Tạo Tensor X có 24 phần tử và reshape theo ba kích thước
X = torch.arange(24)
print("X ban đầu:", X)
print("X reshape 4 x 6:")
print(X.reshape(4, 6))
print("X reshape 2 x 12:")
print(X.reshape(2, 12))
print("X reshape 2 x 3 x 4:")
print(X.reshape(2, 3, 4))

# Các phép toán trên hai Tensor A và B
A = torch.randn(3, 4)
B = torch.randn(3, 4)
print("\nA + B:")
print(A + B)
print("A * B:")
print(A * B)
print("A / B:")
print(A / B)
print("Mean theo cột của A:")
print(torch.mean(A, dim=0))
print("Độ lệch chuẩn theo cột của A:")
print(torch.std(A, dim=0))

# Tính đạo hàm bằng autograd
x_autograd = torch.tensor(2.0, requires_grad=True)
y_autograd = 2 * x_autograd ** 2 + 5 * x_autograd + 3
y_autograd.backward()
print("\n dy/dx bằng autograd:", x_autograd.grad.item())
print(" dy/dx thủ công:", 4 * x_autograd.item() + 5)

# Huấn luyện đa thức y = 2x^2 - 3x + 5
polynomial_11 = np.poly1d([2, -3, 5])
N_11 = 20
X_11 = np.random.randn(N_11, 1) * 5
Y_11 = polynomial_11(X_11)
XX_11 = np.hstack([
    X_11 * X_11,
    X_11,
    np.ones_like(X_11)
])
w_11 = torch.randn(3, 1, requires_grad=True)
x_11 = torch.tensor(XX_11, dtype=torch.float32)
y_11 = torch.tensor(Y_11, dtype=torch.float32)
optimizer_11 = torch.optim.NAdam([w_11], lr=0.01)
for _ in range(5000):
    optimizer_11.zero_grad()
    y_pred_11 = x_11 @ w_11
    mse_11 = torch.mean(torch.square(y_11 - y_pred_11))
    mse_11.backward()
    optimizer_11.step()
print("\nHệ số học được:", w_11.detach().flatten())
print("Hệ số mong đợi:", torch.tensor([2.0, -3.0, 5.0]))

X ban đầu: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
X reshape 4 x 6:
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
X reshape 2 x 12:
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
X reshape 2 x 3 x 4:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

A + B:
tensor([[ 1.9355,  1.2869, -0.1332, -1.2817],
        [-0.8752,  0.2682,  0.5135,  3.2661],
        [ 0.0551, -2.8640, -3.7654, -0.2253]])
A * B:
tensor([[-4.2586e-01,  1.7812e-01, -1.4718e+00,  2.5316e-01],
        [-4.0891e-02, -7.9922e-02, -4.7856e-01,  1.7623e+00],
        [ 6.8865e-04,  1.8985e+00,  2.4501e+00, -3.9803e-01]])
A / B:
tensor([[-10.7035,   7.1572,  -0.8961,   4.2536],
  

## Giải thích

- `X` có `24` phần tử nên có thể reshape thành `4 × 6`, `2 × 12` hoặc `2 × 3 × 4`; tổng số phần tử vẫn giữ nguyên.
- `A + B`, `A * B` và `A / B` đều là phép toán từng phần tử trên hai tensor cùng shape `3 × 4`. Trung bình và độ lệch chuẩn theo cột dùng `dim=0`, nên mỗi kết quả có `4` giá trị.
- Với `y = 2x² + 5x + 3`, ta có `dy/dx = 4x + 5`. Tại `x = 2`, đạo hàm bằng `13`, khớp với kết quả của autograd.
- Đa thức huấn luyện có dạng `2x² - 3x + 5`, vì vậy ba hệ số mong đợi lần lượt là `[2, -3, 5]`. Các hệ số học được sẽ tiến gần các giá trị này.